# Generated by Django 5.1.15 on 2026-06-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_application_material'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationmaterial',
            new_name='application_user_id_9cfb3d_idx',
            old_name='application_user_id_8f0a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationmaterial',
            new_name='application_opportu_e726f2_idx',
            old_name='application_opportu_4c8b1e_idx',
        ),
    ]
