# Generated by Django 5.1.15 on 2026-06-29 06:27

import apps.workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowmessage_metadata_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowmessage',
            name='metadata',
            field=models.JSONField(blank=True, db_default={}, default=apps.workflows.models.empty_metadata),
        ),
    ]
