# Generated by Django 5.1.15 on 2026-06-27 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_opportunity_evaluation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=32)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('target_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_stage', models.CharField(blank=True, max_length=32)),
                ('to_stage', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='applications.application')),
            ],
            options={
                'db_table': 'application_stage_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_name', models.CharField(max_length=128)),
                ('prompt_version', models.PositiveIntegerField(default=1)),
                ('model_name', models.CharField(max_length=128)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('markdown', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_plans', to='applications.application')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_plans', to='jobs.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'stage'], name='application_user_id_24e6ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_application_per_user_opportunity'),
        ),
        migrations.AddIndex(
            model_name='interviewplan',
            index=models.Index(fields=['user', 'status'], name='interview_p_user_id_c80cb3_idx'),
        ),
    ]
