# Generated by Django 5.1.15 on 2026-06-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_interview_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interview',
            new_name='interviews_user_id_334812_idx',
            old_name='interviews_user_id_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='interviews_user_id_815b52_idx',
            old_name='interviews_user_id_4b9e3d_idx',
        ),
    ]
