# Generated by Django 5.1.15 on 2026-06-26 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                ("template", models.TextField()),
                ("variables", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "prompt_versions",
                "ordering": ["name", "-version"],
                "unique_together": {("name", "version")},
            },
        ),
    ]
